package dk.frv.aisrecorder.persistence.domain;

import java.util.Date;

public class AisClassAStatic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_class_a_static.mmsi
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Integer mmsi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_class_a_static.version
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Byte version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_class_a_static.imo
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Integer imo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_class_a_static.pos_type
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Byte posType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_class_a_static.eta
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Date eta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_class_a_static.draught
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Short draught;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_class_a_static.destination
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private String destination;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_class_a_static.dte
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Byte dte;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_class_a_static.mmsi
	 * @return  the value of ais_class_a_static.mmsi
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Integer getMmsi() {
		return mmsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_class_a_static.mmsi
	 * @param mmsi  the value for ais_class_a_static.mmsi
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setMmsi(Integer mmsi) {
		this.mmsi = mmsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_class_a_static.version
	 * @return  the value of ais_class_a_static.version
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Byte getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_class_a_static.version
	 * @param version  the value for ais_class_a_static.version
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setVersion(Byte version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_class_a_static.imo
	 * @return  the value of ais_class_a_static.imo
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Integer getImo() {
		return imo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_class_a_static.imo
	 * @param imo  the value for ais_class_a_static.imo
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setImo(Integer imo) {
		this.imo = imo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_class_a_static.pos_type
	 * @return  the value of ais_class_a_static.pos_type
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Byte getPosType() {
		return posType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_class_a_static.pos_type
	 * @param posType  the value for ais_class_a_static.pos_type
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setPosType(Byte posType) {
		this.posType = posType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_class_a_static.eta
	 * @return  the value of ais_class_a_static.eta
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Date getEta() {
		return eta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_class_a_static.eta
	 * @param eta  the value for ais_class_a_static.eta
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setEta(Date eta) {
		this.eta = eta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_class_a_static.draught
	 * @return  the value of ais_class_a_static.draught
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Short getDraught() {
		return draught;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_class_a_static.draught
	 * @param draught  the value for ais_class_a_static.draught
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setDraught(Short draught) {
		this.draught = draught;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_class_a_static.destination
	 * @return  the value of ais_class_a_static.destination
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public String getDestination() {
		return destination;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_class_a_static.destination
	 * @param destination  the value for ais_class_a_static.destination
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setDestination(String destination) {
		this.destination = destination == null ? null : destination.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_class_a_static.dte
	 * @return  the value of ais_class_a_static.dte
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Byte getDte() {
		return dte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_class_a_static.dte
	 * @param dte  the value for ais_class_a_static.dte
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setDte(Byte dte) {
		this.dte = dte;
	}
}