package dk.frv.aisrecorder.persistence.domain;

import java.util.Date;

public class AisVesselTrack {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_track.id
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_track.mmsi
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Integer mmsi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_track.lat
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Double lat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_track.lon
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Double lon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_track.sog
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Double sog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_track.cog
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Double cog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_track.time
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Date time;
	
	private Date validTo;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_track.created
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	private Date created;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_track.id
	 * @return  the value of ais_vessel_track.id
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_track.id
	 * @param id  the value for ais_vessel_track.id
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_track.mmsi
	 * @return  the value of ais_vessel_track.mmsi
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Integer getMmsi() {
		return mmsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_track.mmsi
	 * @param mmsi  the value for ais_vessel_track.mmsi
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setMmsi(Integer mmsi) {
		this.mmsi = mmsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_track.lat
	 * @return  the value of ais_vessel_track.lat
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Double getLat() {
		return lat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_track.lat
	 * @param lat  the value for ais_vessel_track.lat
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setLat(Double lat) {
		this.lat = lat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_track.lon
	 * @return  the value of ais_vessel_track.lon
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Double getLon() {
		return lon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_track.lon
	 * @param lon  the value for ais_vessel_track.lon
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setLon(Double lon) {
		this.lon = lon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_track.sog
	 * @return  the value of ais_vessel_track.sog
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Double getSog() {
		return sog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_track.sog
	 * @param sog  the value for ais_vessel_track.sog
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setSog(Double sog) {
		this.sog = sog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_track.cog
	 * @return  the value of ais_vessel_track.cog
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Double getCog() {
		return cog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_track.cog
	 * @param cog  the value for ais_vessel_track.cog
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setCog(Double cog) {
		this.cog = cog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_track.time
	 * @return  the value of ais_vessel_track.time
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_track.time
	 * @param time  the value for ais_vessel_track.time
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_track.created
	 * @return  the value of ais_vessel_track.created
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_track.created
	 * @param created  the value for ais_vessel_track.created
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	public void setCreated(Date created) {
		this.created = created;
	}
	
	public Date getValidTo() {
		return validTo;
	}
	
	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}
	
}