package dk.frv.aisrecorder.persistence.domain;

import java.util.Date;

public class AisVesselPosition {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_position.mmsi
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Integer mmsi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_position.lat
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Double lat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_position.lon
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Double lon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_position.pos_acc
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Byte posAcc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_position.sog
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Double sog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_position.cog
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Double cog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_position.heading
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Double heading;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_position.raim
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Byte raim;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_position.utc_sec
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Byte utcSec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_position.source_timestamp
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Date sourceTimestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_position.received
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Date received;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_position.created
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Date created;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_position.mmsi
	 * @return  the value of ais_vessel_position.mmsi
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Integer getMmsi() {
		return mmsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_position.mmsi
	 * @param mmsi  the value for ais_vessel_position.mmsi
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setMmsi(Integer mmsi) {
		this.mmsi = mmsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_position.lat
	 * @return  the value of ais_vessel_position.lat
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Double getLat() {
		return lat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_position.lat
	 * @param lat  the value for ais_vessel_position.lat
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setLat(Double lat) {
		this.lat = lat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_position.lon
	 * @return  the value of ais_vessel_position.lon
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Double getLon() {
		return lon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_position.lon
	 * @param lon  the value for ais_vessel_position.lon
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setLon(Double lon) {
		this.lon = lon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_position.pos_acc
	 * @return  the value of ais_vessel_position.pos_acc
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Byte getPosAcc() {
		return posAcc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_position.pos_acc
	 * @param posAcc  the value for ais_vessel_position.pos_acc
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setPosAcc(Byte posAcc) {
		this.posAcc = posAcc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_position.sog
	 * @return  the value of ais_vessel_position.sog
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Double getSog() {
		return sog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_position.sog
	 * @param sog  the value for ais_vessel_position.sog
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setSog(Double sog) {
		this.sog = sog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_position.cog
	 * @return  the value of ais_vessel_position.cog
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Double getCog() {
		return cog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_position.cog
	 * @param cog  the value for ais_vessel_position.cog
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setCog(Double cog) {
		this.cog = cog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_position.heading
	 * @return  the value of ais_vessel_position.heading
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Double getHeading() {
		return heading;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_position.heading
	 * @param heading  the value for ais_vessel_position.heading
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setHeading(Double heading) {
		this.heading = heading;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_position.raim
	 * @return  the value of ais_vessel_position.raim
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Byte getRaim() {
		return raim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_position.raim
	 * @param raim  the value for ais_vessel_position.raim
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setRaim(Byte raim) {
		this.raim = raim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_position.utc_sec
	 * @return  the value of ais_vessel_position.utc_sec
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Byte getUtcSec() {
		return utcSec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_position.utc_sec
	 * @param utcSec  the value for ais_vessel_position.utc_sec
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setUtcSec(Byte utcSec) {
		this.utcSec = utcSec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_position.source_timestamp
	 * @return  the value of ais_vessel_position.source_timestamp
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Date getSourceTimestamp() {
		return sourceTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_position.source_timestamp
	 * @param sourceTimestamp  the value for ais_vessel_position.source_timestamp
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setSourceTimestamp(Date sourceTimestamp) {
		this.sourceTimestamp = sourceTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_position.received
	 * @return  the value of ais_vessel_position.received
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Date getReceived() {
		return received;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_position.received
	 * @param received  the value for ais_vessel_position.received
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setReceived(Date received) {
		this.received = received;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_position.created
	 * @return  the value of ais_vessel_position.created
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_position.created
	 * @param created  the value for ais_vessel_position.created
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setCreated(Date created) {
		this.created = created;
	}
}