package dk.frv.aisrecorder.persistence.domain;

import java.util.Date;

public class AisVesselStatic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_static.mmsi
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Integer mmsi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_static.name
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_static.callsign
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private String callsign;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_static.ship_type
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Byte shipType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_static.dim_bow
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Short dimBow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_static.dim_stern
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Short dimStern;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_static.dim_port
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Byte dimPort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_static.dim_starboard
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Byte dimStarboard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_static.received
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Date received;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ais_vessel_static.created
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	private Date created;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_static.mmsi
	 * @return  the value of ais_vessel_static.mmsi
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Integer getMmsi() {
		return mmsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_static.mmsi
	 * @param mmsi  the value for ais_vessel_static.mmsi
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setMmsi(Integer mmsi) {
		this.mmsi = mmsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_static.name
	 * @return  the value of ais_vessel_static.name
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_static.name
	 * @param name  the value for ais_vessel_static.name
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_static.callsign
	 * @return  the value of ais_vessel_static.callsign
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public String getCallsign() {
		return callsign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_static.callsign
	 * @param callsign  the value for ais_vessel_static.callsign
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setCallsign(String callsign) {
		this.callsign = callsign == null ? null : callsign.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_static.ship_type
	 * @return  the value of ais_vessel_static.ship_type
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Byte getShipType() {
		return shipType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_static.ship_type
	 * @param shipType  the value for ais_vessel_static.ship_type
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setShipType(Byte shipType) {
		this.shipType = shipType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_static.dim_bow
	 * @return  the value of ais_vessel_static.dim_bow
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Short getDimBow() {
		return dimBow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_static.dim_bow
	 * @param dimBow  the value for ais_vessel_static.dim_bow
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setDimBow(Short dimBow) {
		this.dimBow = dimBow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_static.dim_stern
	 * @return  the value of ais_vessel_static.dim_stern
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Short getDimStern() {
		return dimStern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_static.dim_stern
	 * @param dimStern  the value for ais_vessel_static.dim_stern
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setDimStern(Short dimStern) {
		this.dimStern = dimStern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_static.dim_port
	 * @return  the value of ais_vessel_static.dim_port
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Byte getDimPort() {
		return dimPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_static.dim_port
	 * @param dimPort  the value for ais_vessel_static.dim_port
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setDimPort(Byte dimPort) {
		this.dimPort = dimPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_static.dim_starboard
	 * @return  the value of ais_vessel_static.dim_starboard
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Byte getDimStarboard() {
		return dimStarboard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_static.dim_starboard
	 * @param dimStarboard  the value for ais_vessel_static.dim_starboard
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setDimStarboard(Byte dimStarboard) {
		this.dimStarboard = dimStarboard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_static.received
	 * @return  the value of ais_vessel_static.received
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Date getReceived() {
		return received;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_static.received
	 * @param received  the value for ais_vessel_static.received
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setReceived(Date received) {
		this.received = received;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ais_vessel_static.created
	 * @return  the value of ais_vessel_static.created
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ais_vessel_static.created
	 * @param created  the value for ais_vessel_static.created
	 * @mbggenerated  Wed Dec 07 20:13:18 CET 2011
	 */
	public void setCreated(Date created) {
		this.created = created;
	}
}