package dk.frv.aisrecorder.persistence.mapper;

import dk.frv.aisrecorder.persistence.domain.AisVesselTarget;

public interface AisVesselTargetMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ais_vessel_target
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	int deleteByPrimaryKey(Integer mmsi);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ais_vessel_target
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	int insert(AisVesselTarget record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ais_vessel_target
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	int insertSelective(AisVesselTarget record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ais_vessel_target
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	AisVesselTarget selectByPrimaryKey(Integer mmsi);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ais_vessel_target
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	int updateByPrimaryKeySelective(AisVesselTarget record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ais_vessel_target
	 * @mbggenerated  Thu Dec 08 11:32:48 CET 2011
	 */
	int updateByPrimaryKey(AisVesselTarget record);
}